### ISSUE TITLE
Add WVS.csv

### ISSUE THREAD

**Issue by tszanalytics** [elizavetasemenova/PPLs#1]
Hi, I couldn't find the WVS.csv file, so I tried running the code creating my own fake data, but I wasn't doing the right thing and got an error message.  

I managed to find the R code where you loaded the data and create the .csv, so I ran that.  Since others may not know R, or want to track it down, you may want to add the data file here for easy download.   I would post it here but an issue doesn't seem to accept that kind of file - I can try a pull request but I don't really know what I'm doing!

Thanks for the Julia Turing.jl ordered logistic example.  Very nice!

**Comment by elizavetasemenova** [comment]
Thank you, Jeff. Well spotted concerning the data file - I meant to upload it but forgot. Have moved it to the repo specifically for the ordered logistic model.

**Comment by tszanalytics** [comment]
Great, and great job on the code it is very nice.  I hope to see more
Turing examples soon

 Best,
Jeff
